version: "3.8"

services:
  ws_sispe:
    container_name: ws_sispe
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    mem_limit: 4g
    mem_reservation: 4g
    volumes:
      - ./:/app
      - node_modules:/app/node_modules 
networks:
  api_sispe:
    external: false
    name: network_ws_sispe